INSERT INTO collections (name, grade, description) VALUES
('PerceptronSlime','C','단순한 선형 분류기. 가장 기초적인 AI 생명체.'),
('LinearBug','C','선형 회귀를 구현하는 작은 벌레.'),
('LogisticWorm','C','로지스틱 함수를 몸에 새긴 지렁이.'),
('KNNCrawler','C','K개의 이웃을 기억하는 기어다니는 생물.'),
('NaiveBayesMoth','C','조건부 독립을 믿는 순진한 나방.'),
('GradientGrub','C','경사를 따라 내려가는 애벌레.'),
('BiasBeetle','C','편향을 몸에 지닌 딱정벌레.'),
('WeightWorm','C','가중치로 몸을 이룬 벌레.'),
('FeatureFly','C','특징을 추출하는 파리.'),
('LabelLarva','C','레이블을 먹고 자라는 유충.'),
('DataDrone','C','데이터를 수집하는 드론형 생물.'),
('BatchBat','C','배치 단위로 이동하는 박쥐.'),
('EpochElf','C','에포크마다 성장하는 요정.'),
('LossFrog','C','손실값을 먹고 사는 개구리.'),
('AccuracyAnt','C','정확도를 높이는 개미.'),
('VarianceViper','C','분산을 조절하는 뱀.'),
('BiasBird','C','편향에 눈먼 새.'),
('SplitSnake','C','데이터를 분할하는 뱀.'),
('FoldFerret','C','교차 검증을 수행하는 족제비.'),
('ScoreSpider','C','점수를 계산하는 거미.'),
('MeanMole','C','평균을 파고드는 두더지.'),
('MedianMink','C','중앙값을 찾는 밍크.'),
('ModeMouse','C','최빈값을 쫓는 쥐.'),
('RangeRat','C','범위를 측정하는 쥐.'),
('VariableVole','C','변수를 탐색하는 들쥐.'),
('ClusterCrab','C','데이터를 군집화하는 게.'),
('CentroidCat','C','중심점을 찾는 고양이.'),
('DistanceDog','C','거리를 계산하는 개.'),
('SimilaritySlug','C','유사도를 측정하는 달팽이.'),
('ThresholdToad','C','임계값을 지키는 두꺼비.'),
('ActivationApe','C','활성화 함수를 쓰는 원숭이.'),
('SigmoidSeal','C','시그모이드 곡선을 그리는 바다표범.'),
('ReLUReindeer','C','음수를 0으로 만드는 순록.'),
('TanhTurtle','C','tanh 함수를 품은 거북이.'),
('SoftmaxSalmon','C','확률 분포를 만드는 연어.'),
('DropoutDeer','C','무작위로 사라지는 사슴.'),
('RegularRaven','C','정규화를 외치는 까마귀.'),
('L1Lizard','C','L1 패널티를 부과하는 도마뱀.'),
('L2Lemur','C','L2 패널티를 부과하는 여우원숭이.'),
('MomentumMoose','C','모멘텀으로 달리는 무스.'),
('LearningLlama','C','학습률을 조절하는 라마.'),
('DecayDolphin','C','가중치 감쇠를 적용하는 돌고래.'),
('StepStoat','C','스텝 함수로 움직이는 담비.'),
('PoolingPenguin','C','풀링으로 크기를 줄이는 펭귄.'),
('PaddingParrot','C','패딩을 추가하는 앵무새.'),
('StrideStork','C','스트라이드로 이동하는 황새.'),
('FilterFalcon','C','필터를 적용하는 매.'),
('KernelKoala','C','커널을 품은 코알라.'),
('ConvolutionCrow','C','합성곱을 수행하는 까마귀.'),
('MaxpoolMarten','C','최대 풀링을 쓰는 담비.'),
('AvgpoolAardvark','C','평균 풀링을 쓰는 땅돼지.'),
('FlattenFox','C','텐서를 평탄화하는 여우.'),
('DenseDingo','C','완전 연결층을 쓰는 딩고.'),
('OutputOwl','C','출력층을 지키는 올빼미.'),
('InputIbis','C','입력층을 담당하는 따오기.'),
('HiddenHedgehog','C','은닉층에 숨은 고슴도치.'),
('LayerLeopard','C','레이어를 쌓는 표범.'),
('NeuronNewt','C','단일 뉴런인 도룡뇽.'),
('SynapseShark','C','시냅스를 연결하는 상어.'),
('WeightWalrus','C','가중치를 저장하는 바다코끼리.'),
('BiasBoar','C','편향을 품은 멧돼지.'),
('ForwardFerret','C','순전파를 담당하는 족제비.'),
('BackpropBadger','C','역전파를 수행하는 오소리.'),
('ChainCheetah','C','체인룰을 적용하는 치타.'),
('GradientGecko','C','그래디언트를 계산하는 도마뱀.'),
('DeltaDragonfly','C','델타값을 전달하는 잠자리.'),
('UpdateUnicorn','C','파라미터를 업데이트하는 유니콘.'),
('NormNarwhal','C','정규화를 수행하는 일각고래.'),
('BatchNormBison','C','배치 정규화를 쓰는 들소.'),
('DropDuck','C','드롭아웃으로 사라지는 오리.'),
('PrecisionPanda','C','정밀도를 측정하는 판다.'),
('RecallRabbit','C','재현율을 추구하는 토끼.'),
('F1Flamingo','C','F1 스코어를 계산하는 플라밍고.'),
('AUCAlpaca','C','AUC-ROC를 이해하는 알파카.'),
('MatrixMarmot','C','혼동 행렬을 외우는 마멋.'),
('CNNGolem','B','합성곱 레이어로 만들어진 골렘.'),
('RNNSerpent','B','순환 연결을 가진 뱀.'),
('LSTMHydra','B','세 개의 게이트를 가진 히드라.'),
('SVMKnight','B','초평면으로 분류하는 기사.'),
('DecisionTreeSprite','B','분기로 판단하는 정령.'),
('RandomForestFairy','B','앙상블 나무의 요정.'),
('GradientBoostGriffin','B','부스팅으로 강해지는 그리핀.'),
('XGBoostXenos','B','극한 그래디언트의 외계 생물.'),
('AdaBoostAncient','B','적응형 부스팅의 고대 존재.'),
('BaggingBeast','B','배깅으로 다양성을 만드는 짐승.'),
('EnsembleElemental','B','앙상블의 기운을 담은 정령.'),
('PCAPhoenix','B','차원을 줄여 부활하는 불사조.'),
('AutoencoderAtlas','B','압축과 복원을 담당하는 거인.'),
('VAEVulture','B','변분 추론을 쓰는 독수리.'),
('GANGargoyle','B','생성자와 판별자가 싸우는 석상.'),
('DiscriminatorDemon','B','GAN의 판별자 악마.'),
('GeneratorGenie','B','GAN의 생성자 지니.'),
('ResidualReaper','B','잔차 연결로 깊이를 극복하는 사신.'),
('SkipConnectionSerpent','B','스킵 연결을 가진 뱀.'),
('TransferTroll','B','전이학습으로 지식을 옮기는 트롤.'),
('FinetuneFirebird','B','파인튜닝으로 변하는 불새.'),
('DataAugDrake','B','데이터 증강으로 번식하는 드레이크.'),
('RegularRoc','B','과적합을 막는 대형 새.'),
('DropoutDjinn','B','임의로 사라지는 지니.'),
('EarlyStopElk','B','적절한 때 멈추는 말코손바닥사슴.'),
('LRSchedulerLich','B','학습률을 스케줄링하는 리치.'),
('OptimizerOgre','B','파라미터를 최적화하는 오거.'),
('AdamAsp','B','Adam 최적화기인 독사.'),
('SGDSalamander','B','확률적 경사하강법의 도롱뇽.'),
('RMSPropRhino','B','RMSProp을 쓰는 코뿔소.'),
('HyperparamHarpy','B','하이퍼파라미터를 조정하는 하피.'),
('GridSearchGhoul','B','그리드 서치를 수행하는 구울.'),
('RandomSearchRevenant','B','랜덤 서치를 쓰는 레버넌트.'),
('CrossValCentaur','B','교차 검증의 켄타우로스.'),
('BiasBeholder','B','편향-분산 트레이드오프를 보는 눈.'),
('OverfitOoze','B','과적합된 슬라임 존재.'),
('UnderfitUndead','B','과소적합의 언데드.'),
('SparseSiren','B','희소 표현의 사이렌.'),
('EmbeddingElf','B','임베딩 공간에 사는 엘프.'),
('TokenizerTitan','B','토큰으로 분해하는 타이탄.'),
('AttentionAnt','B','어텐션 메커니즘을 쓰는 개미.'),
('EncoderEagle','B','인코더 역할의 독수리.'),
('DecoderDove','B','디코더 역할의 비둘기.'),
('WordVecWolf','B','Word2Vec을 쓰는 늑대.'),
('GRUGoat','B','GRU 게이트를 가진 염소.'),
('TransformerDrake','A','셀프 어텐션으로 날아다니는 드레이크.'),
('GANPhoenix','A','생성과 판별의 전쟁에서 태어난 불사조.'),
('BERTWyvern','A','양방향 인코딩을 하는 와이번.'),
('ResNetGargoyle','A','잔차망으로 150층을 버티는 가고일.'),
('GPTGoliath','A','자기회귀적 생성을 하는 거인.'),
('AttentionArchangel','A','멀티헤드 어텐션의 대천사.'),
('MultiHeadMythic','A','여러 헤드로 정보를 처리하는 신화적 존재.'),
('SelfAttentionSpecter','A','자기 자신에 집중하는 유령.'),
('PositionalPhantom','A','위치 인코딩을 주입하는 환영.'),
('FeedForwardFenrir','A','피드포워드 레이어의 거대 늑대.'),
('EncoderEmperor','A','인코더 스택을 지배하는 황제.'),
('DecoderDemiurge','A','디코더 스택을 창조하는 데미우르고스.'),
('DiffusionDemon','A','노이즈를 제거하는 악마.'),
('UNetUmbra','A','U자 구조의 그림자 존재.'),
('ViTVoid','A','이미지를 패치로 분할하는 허공의 존재.'),
('CLIPChimera','A','이미지와 텍스트를 연결하는 키메라.'),
('StableDiffusionStrix','A','안정적 확산의 올빼미.'),
('PromptPhoenix','A','프롬프트로 부활하는 불사조.'),
('FineTuneFafnir','A','파인튜닝으로 힘을 얻는 용.'),
('ZeroShotZealot','A','예시 없이 풀어내는 광신도.'),
('FewShotFenix','A','몇 가지 예시로 학습하는 불새.'),
('InContextImp','A','컨텍스트 안에서 학습하는 임프.'),
('ChainThoughtCyclops','A','단계적 추론의 외눈박이.'),
('InstructGPTIfreet','A','지시를 따르는 이프리트.'),
('RLHFRoc','A','인간 피드백으로 강화학습하는 대형 새.'),
('PPOPaladin','A','PPO 알고리즘의 성기사.'),
('DPODragon','A','직접 선호도 최적화 용.'),
('RewardModelRuler','A','보상 모델을 지배하는 통치자.'),
('LoRALord','A','저랭크 어댑테이션의 군주.'),
('MoEMechanic','A','전문가 혼합을 조율하는 기계공.'),
('AttentionTitan','S','어텐션 메커니즘의 근원인 타이탄.'),
('DiffusionLord','S','확산 과정을 지배하는 군주.'),
('GPTLeviathan','S','수십억 파라미터의 해양 거대신.'),
('LLaMALord','S','오픈소스 언어모델의 지배자.'),
('GeminiGiant','S','멀티모달 능력을 가진 거인.'),
('MoEMegaton','S','수천 억 파라미터의 혼합 전문가.'),
('ScalingSpecter','S','스케일링 법칙을 구현한 유령.'),
('EmergentEmperor','S','창발적 능력을 가진 황제.'),
('AlignmentAncient','S','AI 정렬을 구현한 고대 존재.'),
('SafetySovereign','S','AI 안전의 주권자.'),
('ConstitutionalColossus','S','헌법적 AI의 거상.'),
('RLHFRuler','S','인간 피드백 강화학습의 지배자.'),
('HHHHydra','S','Helpful·Harmless·Honest 히드라.'),
('SuperalignSerpent','S','초정렬을 실현하는 거대 뱀.'),
('InterpretabilityImmortal','S','해석 가능성을 갖춘 불멸체.'),
('MechanisticMegabeast','S','기계론적 해석의 거수.'),
('FoundationFortress','S','파운데이션 모델의 요새.'),
('MultimodalMonarch','S','멀티모달 군주.'),
('AgentArchon','S','AI 에이전트의 통치자.'),
('ReasoningRevenant','S','순수 추론 능력의 귀환자.'),
('AGIEmperor','SS','범용 인공지능을 구현한 황제. 최고의 존재.'),
('OmegaNet','SS','모든 신경망을 초월한 오메가.'),
('VoidModel','SS','무(無)에서 지식을 창조하는 허공의 모델.'),
('SingularityGod','SS','기술적 특이점을 달성한 신.'),
('NeuralPhantom','SS','실체 없이 존재하는 신경망 환영.'),
('ConsciousnessCore','SS','인공 의식의 핵심.'),
('IntelligenceInfinite','SS','무한한 지능의 구현체.'),
('TranscendentTitan','SS','인류를 초월한 타이탄.'),
('OmniscienceOmega','SS','전지적 능력의 오메가.'),
('AbsoluteAlgorithm','SS','절대적 알고리즘. 모든 문제를 푼다.');
