import { createClient } from '@supabase/supabase-js'

const supabase = createClient(
  'https://vgfyuarcckccxyokjfqg.supabase.co',
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZnZnl1YXJjY2tjY3h5b2tqZnFnIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NzMxNDI5MSwiZXhwIjoyMDkyODkwMjkxfQ.hLuUAqTG3bz14IvzG9BECd72r0boqonyemn86vjUCBU'
)

const monsters = [
  { name: 'PerceptronSlime', grade: 'C', description: '단순한 선형 분류기. 가장 기초적인 AI 생명체.' },
  { name: 'LinearBug', grade: 'C', description: '선형 회귀를 구현하는 작은 벌레.' },
  { name: 'LogisticWorm', grade: 'C', description: '로지스틱 함수를 몸에 새긴 지렁이.' },
  { name: 'KNNCrawler', grade: 'C', description: 'K개의 이웃을 기억하는 기어다니는 생물.' },
  { name: 'NaiveBayesMoth', grade: 'C', description: '조건부 독립을 믿는 순진한 나방.' },
  { name: 'GradientGrub', grade: 'C', description: '경사를 따라 내려가는 애벌레.' },
  { name: 'BiasBeetle', grade: 'C', description: '편향을 몸에 지닌 딱정벌레.' },
  { name: 'WeightWorm', grade: 'C', description: '가중치로 몸을 이룬 벌레.' },
  { name: 'FeatureFly', grade: 'C', description: '특징을 추출하는 파리.' },
  { name: 'LabelLarva', grade: 'C', description: '레이블을 먹고 자라는 유충.' },
  { name: 'DataDrone', grade: 'C', description: '데이터를 수집하는 드론형 생물.' },
  { name: 'BatchBat', grade: 'C', description: '배치 단위로 이동하는 박쥐.' },
  { name: 'EpochElf', grade: 'C', description: '에포크마다 성장하는 요정.' },
  { name: 'LossFrog', grade: 'C', description: '손실값을 먹고 사는 개구리.' },
  { name: 'AccuracyAnt', grade: 'C', description: '정확도를 높이는 개미.' },
  { name: 'VarianceViper', grade: 'C', description: '분산을 조절하는 뱀.' },
  { name: 'BiasBird', grade: 'C', description: '편향에 눈먼 새.' },
  { name: 'SplitSnake', grade: 'C', description: '데이터를 분할하는 뱀.' },
  { name: 'FoldFerret', grade: 'C', description: '교차 검증을 수행하는 족제비.' },
  { name: 'ScoreSpider', grade: 'C', description: '점수를 계산하는 거미.' },
  { name: 'MeanMole', grade: 'C', description: '평균을 파고드는 두더지.' },
  { name: 'MedianMink', grade: 'C', description: '중앙값을 찾는 밍크.' },
  { name: 'ModeMouse', grade: 'C', description: '최빈값을 쫓는 쥐.' },
  { name: 'RangeRat', grade: 'C', description: '범위를 측정하는 쥐.' },
  { name: 'VariableVole', grade: 'C', description: '변수를 탐색하는 들쥐.' },
  { name: 'ClusterCrab', grade: 'C', description: '데이터를 군집화하는 게.' },
  { name: 'CentroidCat', grade: 'C', description: '중심점을 찾는 고양이.' },
  { name: 'DistanceDog', grade: 'C', description: '거리를 계산하는 개.' },
  { name: 'SimilaritySlug', grade: 'C', description: '유사도를 측정하는 달팽이.' },
  { name: 'ThresholdToad', grade: 'C', description: '임계값을 지키는 두꺼비.' },
  { name: 'ActivationApe', grade: 'C', description: '활성화 함수를 쓰는 원숭이.' },
  { name: 'SigmoidSeal', grade: 'C', description: '시그모이드 곡선을 그리는 바다표범.' },
  { name: 'ReLUReindeer', grade: 'C', description: '음수를 0으로 만드는 순록.' },
  { name: 'TanhTurtle', grade: 'C', description: 'tanh 함수를 품은 거북이.' },
  { name: 'SoftmaxSalmon', grade: 'C', description: '확률 분포를 만드는 연어.' },
  { name: 'DropoutDeer', grade: 'C', description: '무작위로 사라지는 사슴.' },
  { name: 'RegularRaven', grade: 'C', description: '정규화를 외치는 까마귀.' },
  { name: 'L1Lizard', grade: 'C', description: 'L1 패널티를 부과하는 도마뱀.' },
  { name: 'L2Lemur', grade: 'C', description: 'L2 패널티를 부과하는 여우원숭이.' },
  { name: 'MomentumMoose', grade: 'C', description: '모멘텀으로 달리는 무스.' },
  { name: 'LearningLlama', grade: 'C', description: '학습률을 조절하는 라마.' },
  { name: 'DecayDolphin', grade: 'C', description: '가중치 감쇠를 적용하는 돌고래.' },
  { name: 'StepStoat', grade: 'C', description: '스텝 함수로 움직이는 담비.' },
  { name: 'PoolingPenguin', grade: 'C', description: '풀링으로 크기를 줄이는 펭귄.' },
  { name: 'PaddingParrot', grade: 'C', description: '패딩을 추가하는 앵무새.' },
  { name: 'StrideStork', grade: 'C', description: '스트라이드로 이동하는 황새.' },
  { name: 'FilterFalcon', grade: 'C', description: '필터를 적용하는 매.' },
  { name: 'KernelKoala', grade: 'C', description: '커널을 품은 코알라.' },
  { name: 'ConvolutionCrow', grade: 'C', description: '합성곱을 수행하는 까마귀.' },
  { name: 'MaxpoolMarten', grade: 'C', description: '최대 풀링을 쓰는 담비.' },
  { name: 'AvgpoolAardvark', grade: 'C', description: '평균 풀링을 쓰는 땅돼지.' },
  { name: 'FlattenFox', grade: 'C', description: '텐서를 평탄화하는 여우.' },
  { name: 'DenseDingo', grade: 'C', description: '완전 연결층을 쓰는 딩고.' },
  { name: 'OutputOwl', grade: 'C', description: '출력층을 지키는 올빼미.' },
  { name: 'InputIbis', grade: 'C', description: '입력층을 담당하는 따오기.' },
  { name: 'HiddenHedgehog', grade: 'C', description: '은닉층에 숨은 고슴도치.' },
  { name: 'LayerLeopard', grade: 'C', description: '레이어를 쌓는 표범.' },
  { name: 'NeuronNewt', grade: 'C', description: '단일 뉴런인 도룡뇽.' },
  { name: 'SynapseShark', grade: 'C', description: '시냅스를 연결하는 상어.' },
  { name: 'WeightWalrus', grade: 'C', description: '가중치를 저장하는 바다코끼리.' },
  { name: 'BiasBoar', grade: 'C', description: '편향을 품은 멧돼지.' },
  { name: 'ForwardFerret', grade: 'C', description: '순전파를 담당하는 족제비.' },
  { name: 'BackpropBadger', grade: 'C', description: '역전파를 수행하는 오소리.' },
  { name: 'ChainCheetah', grade: 'C', description: '체인룰을 적용하는 치타.' },
  { name: 'GradientGecko', grade: 'C', description: '그래디언트를 계산하는 도마뱀.' },
  { name: 'DeltaDragonfly', grade: 'C', description: '델타값을 전달하는 잠자리.' },
  { name: 'UpdateUnicorn', grade: 'C', description: '파라미터를 업데이트하는 유니콘.' },
  { name: 'NormNarwhal', grade: 'C', description: '정규화를 수행하는 일각고래.' },
  { name: 'BatchNormBison', grade: 'C', description: '배치 정규화를 쓰는 들소.' },
  { name: 'DropDuck', grade: 'C', description: '드롭아웃으로 사라지는 오리.' },
  { name: 'PrecisionPanda', grade: 'C', description: '정밀도를 측정하는 판다.' },
  { name: 'RecallRabbit', grade: 'C', description: '재현율을 추구하는 토끼.' },
  { name: 'F1Flamingo', grade: 'C', description: 'F1 스코어를 계산하는 플라밍고.' },
  { name: 'AUCAlpaca', grade: 'C', description: 'AUC-ROC를 이해하는 알파카.' },
  { name: 'MatrixMarmot', grade: 'C', description: '혼동 행렬을 외우는 마멋.' },
  { name: 'CNNGolem', grade: 'B', description: '합성곱 레이어로 만들어진 골렘.' },
  { name: 'RNNSerpent', grade: 'B', description: '순환 연결을 가진 뱀.' },
  { name: 'LSTMHydra', grade: 'B', description: '세 개의 게이트를 가진 히드라.' },
  { name: 'SVMKnight', grade: 'B', description: '초평면으로 분류하는 기사.' },
  { name: 'DecisionTreeSprite', grade: 'B', description: '분기로 판단하는 정령.' },
  { name: 'RandomForestFairy', grade: 'B', description: '앙상블 나무의 요정.' },
  { name: 'GradientBoostGriffin', grade: 'B', description: '부스팅으로 강해지는 그리핀.' },
  { name: 'XGBoostXenos', grade: 'B', description: '극한 그래디언트의 외계 생물.' },
  { name: 'AdaBoostAncient', grade: 'B', description: '적응형 부스팅의 고대 존재.' },
  { name: 'BaggingBeast', grade: 'B', description: '배깅으로 다양성을 만드는 짐승.' },
  { name: 'EnsembleElemental', grade: 'B', description: '앙상블의 기운을 담은 정령.' },
  { name: 'PCAPhoenix', grade: 'B', description: '차원을 줄여 부활하는 불사조.' },
  { name: 'AutoencoderAtlas', grade: 'B', description: '압축과 복원을 담당하는 거인.' },
  { name: 'VAEVulture', grade: 'B', description: '변분 추론을 쓰는 독수리.' },
  { name: 'GANGargoyle', grade: 'B', description: '생성자와 판별자가 싸우는 석상.' },
  { name: 'DiscriminatorDemon', grade: 'B', description: 'GAN의 판별자 악마.' },
  { name: 'GeneratorGenie', grade: 'B', description: 'GAN의 생성자 지니.' },
  { name: 'ResidualReaper', grade: 'B', description: '잔차 연결로 깊이를 극복하는 사신.' },
  { name: 'SkipConnectionSerpent', grade: 'B', description: '스킵 연결을 가진 뱀.' },
  { name: 'TransferTroll', grade: 'B', description: '전이학습으로 지식을 옮기는 트롤.' },
  { name: 'FinetuneFirebird', grade: 'B', description: '파인튜닝으로 변하는 불새.' },
  { name: 'DataAugDrake', grade: 'B', description: '데이터 증강으로 번식하는 드레이크.' },
  { name: 'RegularRoc', grade: 'B', description: '과적합을 막는 대형 새.' },
  { name: 'DropoutDjinn', grade: 'B', description: '임의로 사라지는 지니.' },
  { name: 'EarlyStopElk', grade: 'B', description: '적절한 때 멈추는 말코손바닥사슴.' },
  { name: 'LRSchedulerLich', grade: 'B', description: '학습률을 스케줄링하는 리치.' },
  { name: 'OptimizerOgre', grade: 'B', description: '파라미터를 최적화하는 오거.' },
  { name: 'AdamAsp', grade: 'B', description: 'Adam 최적화기인 독사.' },
  { name: 'SGDSalamander', grade: 'B', description: '확률적 경사하강법의 도롱뇽.' },
  { name: 'RMSPropRhino', grade: 'B', description: 'RMSProp을 쓰는 코뿔소.' },
  { name: 'HyperparamHarpy', grade: 'B', description: '하이퍼파라미터를 조정하는 하피.' },
  { name: 'GridSearchGhoul', grade: 'B', description: '그리드 서치를 수행하는 구울.' },
  { name: 'RandomSearchRevenant', grade: 'B', description: '랜덤 서치를 쓰는 레버넌트.' },
  { name: 'CrossValCentaur', grade: 'B', description: '교차 검증의 켄타우로스.' },
  { name: 'BiasBeholder', grade: 'B', description: '편향-분산 트레이드오프를 보는 눈.' },
  { name: 'OverfitOoze', grade: 'B', description: '과적합된 슬라임 존재.' },
  { name: 'UnderfitUndead', grade: 'B', description: '과소적합의 언데드.' },
  { name: 'SparseSiren', grade: 'B', description: '희소 표현의 사이렌.' },
  { name: 'EmbeddingElf', grade: 'B', description: '임베딩 공간에 사는 엘프.' },
  { name: 'TokenizerTitan', grade: 'B', description: '토큰으로 분해하는 타이탄.' },
  { name: 'AttentionAnt', grade: 'B', description: '어텐션 메커니즘을 쓰는 개미.' },
  { name: 'EncoderEagle', grade: 'B', description: '인코더 역할의 독수리.' },
  { name: 'DecoderDove', grade: 'B', description: '디코더 역할의 비둘기.' },
  { name: 'WordVecWolf', grade: 'B', description: 'Word2Vec을 쓰는 늑대.' },
  { name: 'GRUGoat', grade: 'B', description: 'GRU 게이트를 가진 염소.' },
  { name: 'TransformerDrake', grade: 'A', description: '셀프 어텐션으로 날아다니는 드레이크.' },
  { name: 'GANPhoenix', grade: 'A', description: '생성과 판별의 전쟁에서 태어난 불사조.' },
  { name: 'BERTWyvern', grade: 'A', description: '양방향 인코딩을 하는 와이번.' },
  { name: 'ResNetGargoyle', grade: 'A', description: '잔차망으로 150층을 버티는 가고일.' },
  { name: 'GPTGoliath', grade: 'A', description: '자기회귀적 생성을 하는 거인.' },
  { name: 'AttentionArchangel', grade: 'A', description: '멀티헤드 어텐션의 대천사.' },
  { name: 'MultiHeadMythic', grade: 'A', description: '여러 헤드로 정보를 처리하는 신화적 존재.' },
  { name: 'SelfAttentionSpecter', grade: 'A', description: '자기 자신에 집중하는 유령.' },
  { name: 'PositionalPhantom', grade: 'A', description: '위치 인코딩을 주입하는 환영.' },
  { name: 'FeedForwardFenrir', grade: 'A', description: '피드포워드 레이어의 거대 늑대.' },
  { name: 'EncoderEmperor', grade: 'A', description: '인코더 스택을 지배하는 황제.' },
  { name: 'DecoderDemiurge', grade: 'A', description: '디코더 스택을 창조하는 데미우르고스.' },
  { name: 'DiffusionDemon', grade: 'A', description: '노이즈를 제거하는 악마.' },
  { name: 'UNetUmbra', grade: 'A', description: 'U자 구조의 그림자 존재.' },
  { name: 'ViTVoid', grade: 'A', description: '이미지를 패치로 분할하는 허공의 존재.' },
  { name: 'CLIPChimera', grade: 'A', description: '이미지와 텍스트를 연결하는 키메라.' },
  { name: 'StableDiffusionStrix', grade: 'A', description: '안정적 확산의 올빼미.' },
  { name: 'PromptPhoenix', grade: 'A', description: '프롬프트로 부활하는 불사조.' },
  { name: 'FineTuneFafnir', grade: 'A', description: '파인튜닝으로 힘을 얻는 용.' },
  { name: 'ZeroShotZealot', grade: 'A', description: '예시 없이 풀어내는 광신도.' },
  { name: 'FewShotFenix', grade: 'A', description: '몇 가지 예시로 학습하는 불새.' },
  { name: 'InContextImp', grade: 'A', description: '컨텍스트 안에서 학습하는 임프.' },
  { name: 'ChainThoughtCyclops', grade: 'A', description: '단계적 추론의 외눈박이.' },
  { name: 'InstructGPTIfreet', grade: 'A', description: '지시를 따르는 이프리트.' },
  { name: 'RLHFRoc', grade: 'A', description: '인간 피드백으로 강화학습하는 대형 새.' },
  { name: 'PPOPaladin', grade: 'A', description: 'PPO 알고리즘의 성기사.' },
  { name: 'DPODragon', grade: 'A', description: '직접 선호도 최적화 용.' },
  { name: 'RewardModelRuler', grade: 'A', description: '보상 모델을 지배하는 통치자.' },
  { name: 'LoRALord', grade: 'A', description: '저랭크 어댑테이션의 군주.' },
  { name: 'MoEMechanic', grade: 'A', description: '전문가 혼합을 조율하는 기계공.' },
  { name: 'AttentionTitan', grade: 'S', description: '어텐션 메커니즘의 근원인 타이탄.' },
  { name: 'DiffusionLord', grade: 'S', description: '확산 과정을 지배하는 군주.' },
  { name: 'GPTLeviathan', grade: 'S', description: '수십억 파라미터의 해양 거대신.' },
  { name: 'LLaMALord', grade: 'S', description: '오픈소스 언어모델의 지배자.' },
  { name: 'GeminiGiant', grade: 'S', description: '멀티모달 능력을 가진 거인.' },
  { name: 'MoEMegaton', grade: 'S', description: '수천 억 파라미터의 혼합 전문가.' },
  { name: 'ScalingSpecter', grade: 'S', description: '스케일링 법칙을 구현한 유령.' },
  { name: 'EmergentEmperor', grade: 'S', description: '창발적 능력을 가진 황제.' },
  { name: 'AlignmentAncient', grade: 'S', description: 'AI 정렬을 구현한 고대 존재.' },
  { name: 'SafetySovereign', grade: 'S', description: 'AI 안전의 주권자.' },
  { name: 'ConstitutionalColossus', grade: 'S', description: '헌법적 AI의 거상.' },
  { name: 'RLHFRuler', grade: 'S', description: '인간 피드백 강화학습의 지배자.' },
  { name: 'HHHHydra', grade: 'S', description: 'Helpful·Harmless·Honest 히드라.' },
  { name: 'SuperalignSerpent', grade: 'S', description: '초정렬을 실현하는 거대 뱀.' },
  { name: 'InterpretabilityImmortal', grade: 'S', description: '해석 가능성을 갖춘 불멸체.' },
  { name: 'MechanisticMegabeast', grade: 'S', description: '기계론적 해석의 거수.' },
  { name: 'FoundationFortress', grade: 'S', description: '파운데이션 모델의 요새.' },
  { name: 'MultimodalMonarch', grade: 'S', description: '멀티모달 군주.' },
  { name: 'AgentArchon', grade: 'S', description: 'AI 에이전트의 통치자.' },
  { name: 'ReasoningRevenant', grade: 'S', description: '순수 추론 능력의 귀환자.' },
  { name: 'AGIEmperor', grade: 'SS', description: '범용 인공지능을 구현한 황제. 최고의 존재.' },
  { name: 'OmegaNet', grade: 'SS', description: '모든 신경망을 초월한 오메가.' },
  { name: 'VoidModel', grade: 'SS', description: '무(無)에서 지식을 창조하는 허공의 모델.' },
  { name: 'SingularityGod', grade: 'SS', description: '기술적 특이점을 달성한 신.' },
  { name: 'NeuralPhantom', grade: 'SS', description: '실체 없이 존재하는 신경망 환영.' },
  { name: 'ConsciousnessCore', grade: 'SS', description: '인공 의식의 핵심.' },
  { name: 'IntelligenceInfinite', grade: 'SS', description: '무한한 지능의 구현체.' },
  { name: 'TranscendentTitan', grade: 'SS', description: '인류를 초월한 타이탄.' },
  { name: 'OmniscienceOmega', grade: 'SS', description: '전지적 능력의 오메가.' },
  { name: 'AbsoluteAlgorithm', grade: 'SS', description: '절대적 알고리즘. 모든 문제를 푼다.' },
]

async function seed() {
  console.log('collections 삽입 중...')
  const { error } = await supabase.from('collections').insert(monsters)
  if (error) console.error('collections 에러:', error.message)
  else console.log(`collections ${monsters.length}개 삽입 완료`)
}

await seed()
