import { createClient } from '@supabase/supabase-js'

const supabase = createClient(
  'https://vgfyuarcckccxyokjfqg.supabase.co',
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZnZnl1YXJjY2tjY3h5b2tqZnFnIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NzMxNDI5MSwiZXhwIjoyMDkyODkwMjkxfQ.hLuUAqTG3bz14IvzG9BECd72r0boqonyemn86vjUCBU'
)

const questions = [
  // Common 20개
  { content: '머신러닝의 세 가지 주요 패러다임을 모두 포함한 것은?', options: ['지도학습, 비지도학습, 강화학습','회귀, 분류, 클러스터링','배치, 온라인, 미니배치','선형, 비선형, 앙상블'], answer: '지도학습, 비지도학습, 강화학습', difficulty: 'common', type: 'multiple', explanation: '머신러닝의 세 패러다임: 레이블 있는 지도학습, 레이블 없는 비지도학습, 보상 기반 강화학습.' },
  { content: '회귀(Regression)와 분류(Classification)의 차이는?', options: ['회귀는 연속값, 분류는 이산값 예측','회귀는 이산값, 분류는 연속값 예측','둘 다 연속값을 예측','둘 다 이산값을 예측'], answer: '회귀는 연속값, 분류는 이산값 예측', difficulty: 'common', type: 'multiple', explanation: '회귀: 주택 가격처럼 연속적인 수치. 분류: 스팸/정상 같은 범주형 레이블 예측.' },
  { content: '혼동 행렬(Confusion Matrix)에서 True Positive(TP)란?', options: ['실제 양성을 양성으로 예측','실제 음성을 양성으로 예측','실제 양성을 음성으로 예측','실제 음성을 음성으로 예측'], answer: '실제 양성을 양성으로 예측', difficulty: 'common', type: 'multiple', explanation: 'TP: 모델이 맞게 양성으로 예측한 경우. FP는 틀리게 양성, FN은 틀리게 음성, TN은 맞게 음성.' },
  { content: '훈련 세트, 검증 세트, 테스트 세트를 나누는 이유는?', options: ['모델 학습, 하이퍼파라미터 조정, 최종 성능 평가를 독립적으로 하기 위해','데이터 양을 늘리기 위해','학습 속도를 높이기 위해','메모리를 절약하기 위해'], answer: '모델 학습, 하이퍼파라미터 조정, 최종 성능 평가를 독립적으로 하기 위해', difficulty: 'common', type: 'multiple', explanation: '테스트 세트를 학습에 사용하면 데이터 누수(data leakage)가 발생해 성능 평가가 불공정해집니다.' },
  { content: '선형 회귀에서 비용 함수(Cost Function)로 MSE를 쓰는 이유는?', options: ['미분 가능하고 볼록 함수라 전역 최솟값 보장','절댓값이라 계산이 쉬움','이상치에 강건함','확률적 해석이 가능함'], answer: '미분 가능하고 볼록 함수라 전역 최솟값 보장', difficulty: 'common', type: 'multiple', explanation: 'MSE는 미분 가능하고 볼록(convex)해서 경사 하강법으로 전역 최솟값을 찾을 수 있습니다.' },
  { content: '원-핫 인코딩(One-Hot Encoding)이 필요한 이유는?', options: ['범주형 변수에 임의의 순서 관계가 생기는 것을 방지','데이터 크기를 줄이기 위해','연속형 변수를 이산화하기 위해','결측값을 처리하기 위해'], answer: '범주형 변수에 임의의 순서 관계가 생기는 것을 방지', difficulty: 'common', type: 'multiple', explanation: '레이블 인코딩(1,2,3)은 순서 관계를 암시하므로, 원-핫 인코딩으로 독립적인 이진 피처를 만듭니다.' },
  { content: '데이터 불균형(Imbalanced Data) 문제 해결 방법이 아닌 것은?', options: ['데이터 정규화','오버샘플링(SMOTE)','클래스 가중치 조정','언더샘플링'], answer: '데이터 정규화', difficulty: 'common', type: 'multiple', explanation: '정규화는 스케일 통일이지 불균형 해결이 아닙니다. 불균형은 샘플링, 가중치, 임계값 조정으로 해결합니다.' },
  { content: '피처 중요도(Feature Importance)를 직접 제공하는 알고리즘은?', options: ['랜덤 포레스트','로지스틱 회귀','KNN','k-means'], answer: '랜덤 포레스트', difficulty: 'common', type: 'multiple', explanation: '트리 기반 모델은 각 분기에서 불순도 감소량으로 피처 중요도를 자동 계산합니다.' },
  { content: '표준화(Standardization)와 Min-Max 정규화의 차이는?', options: ['표준화는 평균 0 분산 1, Min-Max는 0~1 범위로 변환','둘 다 0~1로 변환','표준화는 0~1, Min-Max는 평균 0으로 변환','차이 없음'], answer: '표준화는 평균 0 분산 1, Min-Max는 0~1 범위로 변환', difficulty: 'common', type: 'multiple', explanation: '표준화(Z-score): (x-μ)/σ. Min-Max: (x-min)/(max-min). 이상치에는 표준화가 더 강건합니다.' },
  { content: '결측값(Missing Value) 처리 방법으로 적절하지 않은 것은?', options: ['결측값을 무시하고 모델 학습','평균/중앙값으로 대체','KNN 임퓨테이션','삭제'], answer: '결측값을 무시하고 모델 학습', difficulty: 'common', type: 'multiple', explanation: '대부분의 ML 라이브러리는 결측값을 그냥 두면 에러를 냅니다. 반드시 전처리가 필요합니다.' },
  { content: '부스팅(Boosting)의 핵심 아이디어는?', options: ['이전 모델이 틀린 샘플에 가중치를 높여 순차적으로 학습','독립적 모델을 병렬 학습 후 투표','단일 깊은 트리를 사용','레이어를 점점 깊게 쌓음'], answer: '이전 모델이 틀린 샘플에 가중치를 높여 순차적으로 학습', difficulty: 'common', type: 'multiple', explanation: '부스팅은 약한 학습기를 순차적으로 쌓아 이전 오류에 집중합니다. 배깅과 달리 순차적입니다.' },
  { content: 'ROC 커브에서 AUC가 0.5에 가까울수록 의미하는 것은?', options: ['랜덤 분류기 수준의 성능','완벽한 분류기','최악의 분류기','과적합된 모델'], answer: '랜덤 분류기 수준의 성능', difficulty: 'common', type: 'multiple', explanation: 'AUC=1: 완벽. AUC=0.5: 랜덤 분류(동전 던지기). AUC=0: 완전히 반대로 예측하는 모델.' },
  { content: '하이퍼파라미터와 파라미터의 차이는?', options: ['하이퍼파라미터는 학습 전 사람이 설정, 파라미터는 학습으로 결정','하이퍼파라미터는 가중치, 파라미터는 학습률','둘 다 학습으로 결정','둘 다 사람이 설정'], answer: '하이퍼파라미터는 학습 전 사람이 설정, 파라미터는 학습으로 결정', difficulty: 'common', type: 'multiple', explanation: '파라미터: 가중치·편향(학습으로 업데이트). 하이퍼파라미터: 학습률·배치 크기·레이어 수(사전 설정).' },
  { content: 'K-means 클러스터링의 실제 단점이 아닌 것은?', options: ['대규모 데이터에 느림','K 값을 사전에 지정해야 함','이상치에 민감','구형이 아닌 클러스터 처리 어려움'], answer: '대규모 데이터에 느림', difficulty: 'common', type: 'multiple', explanation: 'K-means는 오히려 대규모 데이터에 상대적으로 빠릅니다. K 사전 지정, 이상치 민감, 구형 가정이 실제 단점입니다.' },
  { content: 'SVM에서 마진(Margin)이란?', options: ['두 클래스 경계 사이의 거리','결정 경계와 가장 먼 점까지의 거리','모든 데이터 포인트의 평균 거리','커널 함수의 출력값'], answer: '두 클래스 경계 사이의 거리', difficulty: 'common', type: 'multiple', explanation: 'SVM은 마진을 최대화하는 초평면을 찾습니다. 마진 위의 점들이 서포트 벡터입니다.' },
  { content: '나이브 베이즈에서 나이브(Naive)가 의미하는 것은?', options: ['모든 피처가 조건부 독립이라고 가정','모델이 단순하다는 의미','학습이 빠르다는 의미','선형 경계를 가진다는 의미'], answer: '모든 피처가 조건부 독립이라고 가정', difficulty: 'common', type: 'multiple', explanation: '실제로 피처 간 상관관계가 있어도 독립으로 가정합니다. 단순하지만 텍스트 분류에서 효과적입니다.' },
  { content: '배치/확률적/미니배치 경사 하강법의 차이는?', options: ['전체/1개/일부 샘플로 그래디언트 계산','학습률이 다름','레이어 수가 다름','정규화 방법이 다름'], answer: '전체/1개/일부 샘플로 그래디언트 계산', difficulty: 'common', type: 'multiple', explanation: '배치GD: 전체 데이터, 안정적이나 느림. SGD: 1개 샘플, 빠르나 불안정. 미니배치: 절충안, 실무에서 사용.' },
  { content: '피처 엔지니어링(Feature Engineering)이 중요한 이유는?', options: ['모델이 학습하기 좋은 표현으로 데이터 변환','항상 딥러닝보다 성능이 좋음','모델 파라미터를 줄임','학습 시간을 단축'], answer: '모델이 학습하기 좋은 표현으로 데이터 변환', difficulty: 'common', type: 'multiple', explanation: '"Garbage in, garbage out." 좋은 피처가 복잡한 모델보다 성능 향상에 더 효과적인 경우가 많습니다.' },
  { content: '협업 필터링(Collaborative Filtering)의 기본 가정은?', options: ['비슷한 취향의 사용자는 비슷한 아이템을 좋아할 것','아이템의 콘텐츠로 추천','인기 있는 아이템을 모두에게 추천','사용자 인구통계로 추천'], answer: '비슷한 취향의 사용자는 비슷한 아이템을 좋아할 것', difficulty: 'common', type: 'multiple', explanation: '유저 기반: 비슷한 유저의 선호를 참고. 아이템 기반: 비슷한 아이템을 찾아 추천. Netflix, Spotify에서 사용.' },
  { content: '사이킷런에서 fit()과 transform()의 차이는?', options: ['fit은 통계 계산, transform은 변환 적용','fit은 모델 학습, transform은 예측','둘 다 같은 기능','fit은 테스트용, transform은 훈련용'], answer: 'fit은 통계 계산, transform은 변환 적용', difficulty: 'common', type: 'multiple', explanation: 'fit: 훈련 데이터 통계(평균, 분산 등) 계산. transform: 계산된 통계로 데이터 변환. 테스트는 fit 없이 transform만 적용.' },

  // Rare 20개
  { content: 'CNN에서 1×1 합성곱의 주요 역할은?', options: ['채널 수 조정 및 계산량 감소','공간 정보 추출','배치 정규화 대체','드롭아웃 효과'], answer: '채널 수 조정 및 계산량 감소', difficulty: 'rare', type: 'multiple', explanation: 'Inception 모듈에서 1×1 conv는 채널을 줄여 계산량을 감소시킵니다. 채널 간 선형 결합 역할도 합니다.' },
  { content: 'Transformer에서 포지셔널 인코딩이 필요한 이유는?', options: ['셀프 어텐션 자체는 순서 정보가 없기 때문','RNN보다 느리기 때문','메모리 절약을 위해','배치 크기를 늘리기 위해'], answer: '셀프 어텐션 자체는 순서 정보가 없기 때문', difficulty: 'rare', type: 'multiple', explanation: '어텐션은 위치를 고려하지 않는 집합 연산입니다. sin/cos 함수로 위치 정보를 임베딩에 더해줍니다.' },
  { content: '임베딩(Embedding)이란?', options: ['고차원 이산 데이터를 저차원 연속 벡터로 변환','이미지를 텍스트로 변환','데이터를 압축 저장','모델을 경량화'], answer: '고차원 이산 데이터를 저차원 연속 벡터로 변환', difficulty: 'rare', type: 'multiple', explanation: '단어 임베딩: 5만 단어 원-핫 → 300차원 밀집 벡터. 의미적으로 유사한 단어는 벡터 공간에서 가깝습니다.' },
  { content: 'RNN의 기울기 소실 문제가 발생하는 원인은?', options: ['시간 축으로 역전파 시 작은 값이 반복 곱해져 0에 수렴','레이어가 너무 많아서','배치 크기가 너무 커서','학습률이 너무 낮아서'], answer: '시간 축으로 역전파 시 작은 값이 반복 곱해져 0에 수렴', difficulty: 'rare', type: 'multiple', explanation: 'BPTT에서 그래디언트가 타임 스텝마다 가중치 행렬과 곱해지므로 σ<1인 값이 반복 곱해져 소실됩니다.' },
  { content: '배치 정규화(Batch Normalization)를 적용하는 위치는?', options: ['일반적으로 선형 변환 후, 활성화 함수 전','입력 레이어에만','출력 레이어에만','손실 함수 직전'], answer: '일반적으로 선형 변환 후, 활성화 함수 전', difficulty: 'rare', type: 'multiple', explanation: '원 논문은 활성화 전을 권장하지만 실제로는 두 위치 모두 사용됩니다. 내부 공변량 이동을 줄입니다.' },
  { content: '배깅(Bagging)이 과적합을 줄이는 원리는?', options: ['다양한 부트스트랩 샘플로 학습한 모델의 예측을 평균화하여 분산 감소','순차적으로 오류를 수정','단일 모델을 반복 학습','데이터를 증강'], answer: '다양한 부트스트랩 샘플로 학습한 모델의 예측을 평균화하여 분산 감소', difficulty: 'rare', type: 'multiple', explanation: '배깅은 고분산 모델(깊은 트리)의 분산을 줄입니다. 여러 모델의 평균은 단일 모델보다 안정적입니다.' },
  { content: 'BERT 사전 학습에 사용되는 두 가지 태스크는?', options: ['Masked LM + Next Sentence Prediction','다음 단어 예측 + 감성 분류','번역 + 요약','이미지 분류 + 텍스트 생성'], answer: 'Masked LM + Next Sentence Prediction', difficulty: 'rare', type: 'multiple', explanation: 'MLM: 입력 토큰의 15%를 마스킹하고 예측. NSP: 두 문장이 연속인지 예측. 양방향 문맥을 학습합니다.' },
  { content: '소프트맥스(Softmax)의 수식 특징은?', options: ['모든 출력값의 합이 1이 됨','출력값이 0 또는 1','음수를 0으로 변환','입력 범위를 -1~1로 제한'], answer: '모든 출력값의 합이 1이 됨', difficulty: 'rare', type: 'multiple', explanation: 'Softmax(xᵢ) = exp(xᵢ)/Σexp(xⱼ). 출력이 확률 분포가 되어 다중 클래스 분류의 최종 레이어에 사용됩니다.' },
  { content: '교차 엔트로피 손실(Cross-Entropy Loss)이 분류에 적합한 이유는?', options: ['예측 확률 분포와 실제 분포의 차이를 측정하며 오답에 강한 패널티','MSE보다 계산이 빠름','음수 값을 처리할 수 있음','회귀에도 사용 가능'], answer: '예측 확률 분포와 실제 분포의 차이를 측정하며 오답에 강한 패널티', difficulty: 'rare', type: 'multiple', explanation: '-log(p)는 확신했는데 틀렸을 때 매우 큰 손실을 줍니다. Softmax와 함께 분류 표준으로 사용됩니다.' },
  { content: '데이터 증강(Data Augmentation)이 효과적인 이유는?', options: ['모델이 보는 샘플 다양성을 높여 일반화 향상','레이블을 자동 생성','모델 파라미터 감소','학습 속도 향상'], answer: '모델이 보는 샘플 다양성을 높여 일반화 향상', difficulty: 'rare', type: 'multiple', explanation: '이미지: 회전·반전·크롭·색상 변환. 텍스트: 동의어 교체·역번역. 오버피팅 방지에 매우 효과적입니다.' },
  { content: '오토인코더(Autoencoder)의 인코더와 디코더의 역할은?', options: ['인코더: 압축, 디코더: 복원','인코더: 분류, 디코더: 생성','인코더: 노이즈 추가, 디코더: 제거','인코더: 예측, 디코더: 평가'], answer: '인코더: 압축, 디코더: 복원', difficulty: 'rare', type: 'multiple', explanation: '인코더가 입력을 저차원 잠재 공간으로 압축하고, 디코더가 복원합니다. 비지도 표현 학습에 사용됩니다.' },
  { content: '가중치 초기화(Weight Initialization)가 중요한 이유는?', options: ['잘못된 초기화는 기울기 소실/폭발을 유발','메모리 절약','학습률 자동 설정','배치 크기 결정'], answer: '잘못된 초기화는 기울기 소실/폭발을 유발', difficulty: 'rare', type: 'multiple', explanation: '모든 0 초기화: 모든 뉴런이 같은 그래디언트 → 대칭성 문제. Xavier/He 초기화로 적절한 분산을 설정합니다.' },
  { content: 'Seq2Seq 모델에서 어텐션 메커니즘의 역할은?', options: ['디코더가 인코더의 모든 은닉 상태를 동적으로 참조','인코더 출력을 고정 벡터로 압축','배치 정규화를 대체','드롭아웃 효과'], answer: '디코더가 인코더의 모든 은닉 상태를 동적으로 참조', difficulty: 'rare', type: 'multiple', explanation: '기존 Seq2Seq는 고정 크기 벡터가 병목. 어텐션으로 긴 시퀀스에서도 관련 부분에 집중할 수 있습니다.' },
  { content: 'Precision과 Recall 사이의 트레이드오프는?', options: ['임계값을 높이면 Precision 증가, Recall 감소','임계값을 높이면 둘 다 증가','임계값을 낮추면 Precision 증가','두 지표는 독립적'], answer: '임계값을 높이면 Precision 증가, Recall 감소', difficulty: 'rare', type: 'multiple', explanation: '임계값↑: 더 확실할 때만 양성 예측 → FP↓ Precision↑, FN↑ Recall↓. F1은 둘의 조화 평균입니다.' },
  { content: '그래디언트 클리핑(Gradient Clipping)의 목적은?', options: ['기울기 폭발(Exploding Gradient) 방지','기울기 소실 방지','학습률 자동 조정','배치 정규화 대체'], answer: '기울기 폭발(Exploding Gradient) 방지', difficulty: 'rare', type: 'multiple', explanation: '그래디언트의 norm이 임계값을 초과하면 스케일을 줄입니다. RNN 학습에서 특히 중요합니다.' },
  { content: '전이학습 파인튜닝 시 일반적인 전략은?', options: ['초반 레이어는 동결, 후반 레이어만 학습','모든 레이어를 처음부터 학습','모든 레이어를 동결','학습률을 매우 높게 설정'], answer: '초반 레이어는 동결, 후반 레이어만 학습', difficulty: 'rare', type: 'multiple', explanation: '초반 레이어는 일반적 특징(엣지, 곡선)을 학습하므로 재사용. 후반 레이어는 태스크 특화 특징이므로 파인튜닝합니다.' },
  { content: '모델 압축 기법 중 양자화(Quantization)란?', options: ['가중치를 낮은 비트로 표현해 모델 크기 축소','레이어를 제거','채널 수를 줄임','지식 증류를 사용'], answer: '가중치를 낮은 비트로 표현해 모델 크기 축소', difficulty: 'rare', type: 'multiple', explanation: 'FP32 → INT8으로 양자화하면 모델 크기 4배 감소, 추론 속도 향상. 정확도 손실은 최소화됩니다.' },
  { content: '레이블 스무딩(Label Smoothing)의 목적은?', options: ['모델이 지나치게 확신하는 것을 방지해 일반화 향상','학습 속도 향상','데이터 불균형 해결','결측값 처리'], answer: '모델이 지나치게 확신하는 것을 방지해 일반화 향상', difficulty: 'rare', type: 'multiple', explanation: '원-핫 레이블(0,1) 대신 부드러운 레이블(0.1, 0.9)을 사용. 모델의 과신(overconfidence)을 줄입니다.' },
  { content: 't-SNE의 주요 용도는?', options: ['고차원 데이터의 2D/3D 시각화','차원 축소 후 분류','클러스터링','이상치 탐지'], answer: '고차원 데이터의 2D/3D 시각화', difficulty: 'rare', type: 'multiple', explanation: 't-SNE는 비선형 차원 축소로 고차원 데이터의 클러스터 구조를 2D로 시각화합니다. PCA와 달리 전역 구조는 보존하지 않습니다.' },
  { content: '워드 임베딩에서 유추(Analogy) 태스크란?', options: ['king-man+woman=queen처럼 벡터 연산으로 관계 추론','단어 빈도 계산','문장 생성','감성 분석'], answer: 'king-man+woman=queen처럼 벡터 연산으로 관계 추론', difficulty: 'rare', type: 'multiple', explanation: 'Word2Vec 임베딩 공간에서 의미 관계가 벡터 방향으로 인코딩됩니다. 젠더, 국가-수도 관계 등이 선형 구조로 나타납니다.' },

  // Epic 15개
  { content: 'Transformer 멀티헤드 어텐션(Multi-Head Attention)의 이점은?', options: ['다양한 표현 부공간에서 병렬로 정보를 추출','계산량을 줄임','메모리를 줄임','단일 어텐션보다 항상 느림'], answer: '다양한 표현 부공간에서 병렬로 정보를 추출', difficulty: 'epic', type: 'multiple', explanation: 'h개 헤드가 서로 다른 관점(구문, 의미, 위치 등)으로 어텐션을 계산하고 concat합니다. 표현력이 풍부해집니다.' },
  { content: 'LLM의 인컨텍스트 학습(In-Context Learning)이란?', options: ['추가 학습 없이 프롬프트 내 예시만으로 새 태스크 수행','파인튜닝의 다른 이름','지속적 학습 방법','강화학습 기법'], answer: '추가 학습 없이 프롬프트 내 예시만으로 새 태스크 수행', difficulty: 'epic', type: 'multiple', explanation: 'GPT-3가 발견한 창발적 능력. 가중치 업데이트 없이 Few-shot 예시로 번역, 코딩, 추론 등 다양한 태스크를 수행합니다.' },
  { content: 'Stable Diffusion의 잠재 확산(Latent Diffusion)이 기존 확산 모델과 다른 점은?', options: ['픽셀 공간이 아닌 잠재 공간에서 확산 수행해 계산 효율적','더 많은 파라미터 사용','텍스트 조건 없음','단계 수가 더 많음'], answer: '픽셀 공간이 아닌 잠재 공간에서 확산 수행해 계산 효율적', difficulty: 'epic', type: 'multiple', explanation: 'VAE 인코더로 이미지를 잠재 공간으로 압축 후 확산 모델을 적용합니다. 고해상도 이미지 생성이 실용적으로 가능해졌습니다.' },
  { content: 'KV 캐시(KV Cache)가 LLM 추론에서 중요한 이유는?', options: ['자기회귀 생성 시 이전 토큰의 Key-Value를 재계산하지 않아 속도 향상','모델 크기 감소','정확도 향상','배치 처리 가능'], answer: '자기회귀 생성 시 이전 토큰의 Key-Value를 재계산하지 않아 속도 향상', difficulty: 'epic', type: 'multiple', explanation: '토큰을 하나씩 생성할 때마다 전체 시퀀스의 K/V를 재계산하면 O(n²) 복잡도. 캐싱으로 O(n)으로 줄입니다.' },
  { content: '파운데이션 모델(Foundation Model)의 특징은?', options: ['대규모 데이터로 사전학습하고 다양한 태스크에 적응 가능','단일 태스크에 특화','소규모 데이터로 학습','파인튜닝 불가'], answer: '대규모 데이터로 사전학습하고 다양한 태스크에 적응 가능', difficulty: 'epic', type: 'multiple', explanation: 'Stanford 2021년 제안. GPT, BERT, CLIP 등. 한 번 사전학습으로 번역, 요약, 질답, 코드 생성 등 다목적 활용 가능합니다.' },
  { content: 'Few-shot과 Zero-shot의 차이는?', options: ['Few-shot은 예시 포함, Zero-shot은 예시 없이 설명만','Few-shot이 항상 좋음','Zero-shot은 파인튜닝 필요','둘 다 동일'], answer: 'Few-shot은 예시 포함, Zero-shot은 예시 없이 설명만', difficulty: 'epic', type: 'multiple', explanation: 'Zero-shot: "번역해줘". Few-shot: "A→B 예시 3개를 보여주고 번역해줘". 복잡한 태스크일수록 Few-shot이 유리합니다.' },
  { content: 'LLM에서 토큰(Token)이란?', options: ['텍스트를 모델이 처리하는 단위로 분할한 것 (단어·서브워드·문자)','문장 전체','단어와 동일','바이트와 동일'], answer: '텍스트를 모델이 처리하는 단위로 분할한 것 (단어·서브워드·문자)', difficulty: 'epic', type: 'multiple', explanation: 'GPT-4는 BPE 토크나이저 사용. "unhappiness" → ["un","happy","ness"] 3토큰. 한국어는 영어보다 토큰 수가 많습니다.' },
  { content: 'RAG(Retrieval-Augmented Generation)의 핵심 아이디어는?', options: ['외부 지식 베이스에서 관련 문서를 검색해 LLM 컨텍스트에 추가','모델을 지속적으로 재학습','파인튜닝의 대안','프롬프트를 자동 생성'], answer: '외부 지식 베이스에서 관련 문서를 검색해 LLM 컨텍스트에 추가', difficulty: 'epic', type: 'multiple', explanation: 'LLM의 지식 한계와 환각(hallucination)을 줄입니다. 벡터 DB + 임베딩 검색 + LLM 생성으로 구성됩니다.' },
  { content: '모델 증류(Knowledge Distillation)란?', options: ['큰 교사 모델의 소프트 레이블로 작은 학생 모델을 학습','모델의 레이어를 제거','가중치를 양자화','앙상블 기법'], answer: '큰 교사 모델의 소프트 레이블로 작은 학생 모델을 학습', difficulty: 'epic', type: 'multiple', explanation: '소프트 레이블(확률 분포)은 하드 레이블보다 더 많은 정보를 포함합니다. DistilBERT는 BERT 크기의 60%지만 성능 97% 유지합니다.' },
  { content: 'AI 에이전트에서 ReAct 프레임워크란?', options: ['Reasoning과 Acting을 번갈아 수행해 복잡한 태스크 해결','반응형 AI의 약자','강화학습 기법','멀티모달 처리 방법'], answer: 'Reasoning과 Acting을 번갈아 수행해 복잡한 태스크 해결', difficulty: 'epic', type: 'multiple', explanation: '생각(Thought) → 행동(Action) → 관찰(Observation)을 반복하며 외부 도구를 사용해 복잡한 문제를 해결합니다.' },
  { content: '컨텍스트 윈도우(Context Window) 크기가 중요한 이유는?', options: ['모델이 한 번에 처리할 수 있는 최대 토큰 수로 긴 문서 처리 능력 결정','모델 파라미터 수 결정','학습 속도 결정','배치 크기와 동일'], answer: '모델이 한 번에 처리할 수 있는 최대 토큰 수로 긴 문서 처리 능력 결정', difficulty: 'epic', type: 'multiple', explanation: 'GPT-4: 128k 토큰, Claude: 200k 토큰. 긴 문서 요약, 코드베이스 분석 시 컨텍스트가 클수록 유리합니다.' },
  { content: '멀티모달(Multimodal) AI 모델이란?', options: ['텍스트, 이미지, 오디오 등 여러 형태의 데이터를 처리하는 모델','여러 언어를 처리하는 모델','앙상블 모델의 다른 이름','다중 GPU를 사용하는 모델'], answer: '텍스트, 이미지, 오디오 등 여러 형태의 데이터를 처리하는 모델', difficulty: 'epic', type: 'multiple', explanation: 'GPT-4V, Gemini, Claude 등. 이미지+텍스트 입력으로 시각적 질문 답변, 차트 해석, 이미지 생성 등이 가능합니다.' },
  { content: 'AI 환각(Hallucination) 문제란?', options: ['LLM이 사실과 다른 그럴듯한 내용을 생성하는 현상','모델이 느려지는 현상','과적합의 다른 이름','데이터 누수 문제'], answer: 'LLM이 사실과 다른 그럴듯한 내용을 생성하는 현상', difficulty: 'epic', type: 'multiple', explanation: '언어 모델은 다음 토큰 확률 최적화로 학습하므로 사실성보다 유창성이 우선됩니다. RAG, RLHF, 팩트 체킹으로 완화합니다.' },
  { content: '벡터 데이터베이스(Vector Database)가 AI 애플리케이션에서 중요한 이유는?', options: ['임베딩 벡터의 유사도 검색을 효율적으로 수행하기 위해','SQL 쿼리 최적화','그래프 데이터 저장','실시간 스트리밍 처리'], answer: '임베딩 벡터의 유사도 검색을 효율적으로 수행하기 위해', difficulty: 'epic', type: 'multiple', explanation: 'RAG 시스템의 핵심 컴포넌트. Pinecone, Weaviate, Chroma 등. HNSW, IVF 인덱스로 수백만 벡터의 ANN 검색을 지원합니다.' },
  { content: 'AI 모델의 추론(Inference) 최적화 기법이 아닌 것은?', options: ['데이터 증강','양자화(Quantization)','모델 프루닝(Pruning)','배치 처리'], answer: '데이터 증강', difficulty: 'epic', type: 'multiple', explanation: '데이터 증강은 학습 시 사용하는 기법입니다. 추론 최적화: 양자화, 프루닝, 지식 증류, KV 캐시, 배치 처리, 컴파일 최적화 등입니다.' },

  // Legendary 10개
  { content: 'Anthropic의 스케일링 법칙 연구가 시사하는 것은?', options: ['모델 크기, 데이터, 컴퓨팅의 균형 잡힌 스케일업이 성능 향상','모델 크기만 늘리면 됨','데이터만 늘리면 됨','알고리즘 개선이 스케일링보다 중요'], answer: '모델 크기, 데이터, 컴퓨팅의 균형 잡힌 스케일업이 성능 향상', difficulty: 'legendary', type: 'multiple', explanation: 'Chinchilla 법칙: N파라미터 모델엔 20N 토큰이 최적. GPT-3는 과소학습 상태였습니다. 균형 있는 스케일링이 중요합니다.' },
  { content: 'AI 안전성에서 정렬(Alignment) 문제란?', options: ['AI 시스템이 인간의 의도와 가치에 부합하게 행동하도록 만드는 문제','모델 성능을 높이는 문제','데이터 품질 문제','컴퓨팅 효율 문제'], answer: 'AI 시스템이 인간의 의도와 가치에 부합하게 행동하도록 만드는 문제', difficulty: 'legendary', type: 'multiple', explanation: '능력이 뛰어난 AI가 잘못된 목표를 추구하면 큰 위험이 됩니다. RLHF, Constitutional AI, 해석 가능성 연구로 접근합니다.' },
  { content: '모델 평가에서 벤치마크(Benchmark)의 한계는?', options: ['데이터 오염, 오버피팅, 실제 사용 시나리오와의 불일치','벤치마크가 항상 정확','소수 태스크만 평가','계산이 복잡'], answer: '데이터 오염, 오버피팅, 실제 사용 시나리오와의 불일치', difficulty: 'legendary', type: 'multiple', explanation: '학습 데이터에 벤치마크가 포함되면 데이터 오염. 좋은 벤치마크 점수 ≠ 실제 유용성. MMLU, HumanEval도 이 문제에서 자유롭지 않습니다.' },
  { content: 'AI 에이전트에서 도구 사용(Tool Use)의 중요성은?', options: ['LLM의 지식 한계와 연산 능력을 보완해 실세계 작업 수행 가능','모델 파라미터를 줄임','학습 속도 향상','환각을 완전히 제거'], answer: 'LLM의 지식 한계와 연산 능력을 보완해 실세계 작업 수행 가능', difficulty: 'legendary', type: 'multiple', explanation: '계산기, 웹 검색, 코드 실행, DB 쿼리 등의 도구를 사용하면 LLM이 정확한 수학 계산, 최신 정보 검색이 가능해집니다.' },
  { content: '강화학습에서 탐색(Exploration)과 활용(Exploitation)의 트레이드오프란?', options: ['새로운 행동 시도 vs 알려진 최선 행동 선택 간의 균형','학습률 선택','배치 크기 선택','보상 함수 설계'], answer: '새로운 행동 시도 vs 알려진 최선 행동 선택 간의 균형', difficulty: 'legendary', type: 'multiple', explanation: '탐색만 하면 최적 정책을 활용 못함. 활용만 하면 더 좋은 정책을 발견 못함. ε-greedy, UCB, Thompson Sampling으로 균형을 맞춥니다.' },
  { content: '멀티모달 LLM에서 비전-언어 정렬(Vision-Language Alignment)이란?', options: ['이미지와 텍스트 임베딩 공간을 연결해 상호 이해 가능하게 만드는 기술','이미지를 텍스트로 변환','텍스트를 이미지로 변환','음성 처리 기술'], answer: '이미지와 텍스트 임베딩 공간을 연결해 상호 이해 가능하게 만드는 기술', difficulty: 'legendary', type: 'multiple', explanation: 'CLIP은 이미지-텍스트 쌍으로 대조 학습. LLaVA는 CLIP 비전 인코더 + LLM 구조. 두 모달리티의 공통 표현 공간을 만듭니다.' },
  { content: 'AI의 창발적 능력(Emergent Abilities)이 논쟁적인 이유는?', options: ['측정 방법에 따라 창발이 아닌 연속적 향상일 수 있기 때문','창발이 불가능해서','소형 모델에도 나타나서','측정이 쉬워서'], answer: '측정 방법에 따라 창발이 아닌 연속적 향상일 수 있기 때문', difficulty: 'legendary', type: 'multiple', explanation: 'Stanford 2022 vs Google 2023 논쟁: 이진 메트릭을 연속 메트릭으로 바꾸면 창발이 아닌 선형 향상처럼 보일 수 있습니다.' },
  { content: '프론티어 모델(Frontier Model)의 위험 평가가 중요한 이유는?', options: ['능력이 급격히 향상되면서 새로운 위험(사이버, 생물, CBRN)이 출현할 수 있기 때문','모델 크기 때문','학습 비용 때문','환경 영향 때문'], answer: '능력이 급격히 향상되면서 새로운 위험(사이버, 생물, CBRN)이 출현할 수 있기 때문', difficulty: 'legendary', type: 'multiple', explanation: 'Anthropic의 RSP, OpenAI의 안전 평가 프레임워크. 특정 위험 임계점을 넘으면 배포를 중단하는 조건부 배포 정책입니다.' },
  { content: '뉴럴 스케일링에서 power law가 의미하는 것은?', options: ['성능이 모델 크기/데이터/컴퓨팅의 거듭제곱에 비례해 향상','성능이 선형적으로 향상','일정 크기 이상에서 성능이 감소','랜덤하게 향상'], answer: '성능이 모델 크기/데이터/컴퓨팅의 거듭제곱에 비례해 향상', difficulty: 'legendary', type: 'multiple', explanation: 'Loss ∝ N^(-α). 10배 컴퓨팅 증가 → 일정 비율로 loss 감소. 이 예측 가능한 규칙성이 대규모 투자를 정당화합니다.' },
  { content: 'AI 해석 가능성에서 회로(Circuit) 분석이란?', options: ['특정 행동을 유발하는 신경망 내부의 알고리즘적 구조를 역공학','회로 기판 최적화','전력 효율화','하드웨어 설계'], answer: '특정 행동을 유발하는 신경망 내부의 알고리즘적 구조를 역공학', difficulty: 'legendary', type: 'multiple', explanation: 'Anthropic 연구: 인덕션 헤드(복사), 간접 객체 식별 회로 발견. 모델이 실제로 어떻게 추론하는지 이해하는 기계론적 접근법입니다.' },
]

console.log(`총 ${questions.length}개 문제 삽입 중...`)
const { error } = await supabase.from('questions').insert(questions)
if (error) console.error('에러:', error.message)
else console.log('삽입 완료!')

const { count } = await supabase.from('questions').select('*', { count: 'exact', head: true })
console.log(`현재 DB 문제 수: ${count}`)
